/// All same name icons of material and cupertino.
/// This file generated by script, do not edit this file directly.

/// Local SDK version information:
/// Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
/// Framework • revision f468f3366c (5 days ago) • 2023-07-12 15:19:05 -0700
/// Engine • revision cdbeda788a
/// Tools • Dart 3.0.6 • DevTools 2.23.1

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'platform.dart';
import 'platform_icons.dart';

extension PlatformIconsGen on PlatformIcons {
  /// Icons: Icons.add : CupertinoIcons.add
  IconData get add => isMaterial() ? Icons.add : CupertinoIcons.add;

  /// Icons: Icons.alarm : CupertinoIcons.alarm
  IconData get alarm => isMaterial() ? Icons.alarm : CupertinoIcons.alarm;

  /// Icons: Icons.arrow_left : CupertinoIcons.arrow_left
  IconData get arrowLeft =>
      isMaterial() ? Icons.arrow_left : CupertinoIcons.arrow_left;

  /// Icons: Icons.arrow_right : CupertinoIcons.arrow_right
  IconData get arrowRight =>
      isMaterial() ? Icons.arrow_right : CupertinoIcons.arrow_right;

  /// Icons: Icons.battery_full : CupertinoIcons.battery_full
  IconData get batteryFull =>
      isMaterial() ? Icons.battery_full : CupertinoIcons.battery_full;

  /// Icons: Icons.bluetooth : CupertinoIcons.bluetooth
  IconData get bluetooth =>
      isMaterial() ? Icons.bluetooth : CupertinoIcons.bluetooth;

  /// Icons: Icons.bolt : CupertinoIcons.bolt
  IconData get bolt => isMaterial() ? Icons.bolt : CupertinoIcons.bolt;

  /// Icons: Icons.book : CupertinoIcons.book
  IconData get book => isMaterial() ? Icons.book : CupertinoIcons.book;

  /// Icons: Icons.bookmark : CupertinoIcons.bookmark
  IconData get bookmark =>
      isMaterial() ? Icons.bookmark : CupertinoIcons.bookmark;

  /// Icons: Icons.calendar_today : CupertinoIcons.calendar_today
  IconData get calendarToday =>
      isMaterial() ? Icons.calendar_today : CupertinoIcons.calendar_today;

  /// Icons: Icons.camera : CupertinoIcons.camera
  IconData get camera => isMaterial() ? Icons.camera : CupertinoIcons.camera;

  /// Icons: Icons.chat_bubble : CupertinoIcons.chat_bubble
  IconData get chatBubble =>
      isMaterial() ? Icons.chat_bubble : CupertinoIcons.chat_bubble;

  /// Icons: Icons.chevron_left : CupertinoIcons.chevron_left
  IconData get chevronLeft =>
      isMaterial() ? Icons.chevron_left : CupertinoIcons.chevron_left;

  /// Icons: Icons.chevron_right : CupertinoIcons.chevron_right
  IconData get chevronRight =>
      isMaterial() ? Icons.chevron_right : CupertinoIcons.chevron_right;

  /// Icons: Icons.circle : CupertinoIcons.circle
  IconData get circle => isMaterial() ? Icons.circle : CupertinoIcons.circle;

  /// Icons: Icons.clear : CupertinoIcons.clear
  IconData get clear => isMaterial() ? Icons.clear : CupertinoIcons.clear;

  /// Icons: Icons.cloud : CupertinoIcons.cloud
  IconData get cloud => isMaterial() ? Icons.cloud : CupertinoIcons.cloud;

  /// Icons: Icons.cloud_download : CupertinoIcons.cloud_download
  IconData get cloudDownload =>
      isMaterial() ? Icons.cloud_download : CupertinoIcons.cloud_download;

  /// Icons: Icons.cloud_upload : CupertinoIcons.cloud_upload
  IconData get cloudUpload =>
      isMaterial() ? Icons.cloud_upload : CupertinoIcons.cloud_upload;

  /// Icons: Icons.collections : CupertinoIcons.collections
  IconData get collections =>
      isMaterial() ? Icons.collections : CupertinoIcons.collections;

  /// Icons: Icons.create : CupertinoIcons.create
  IconData get create => isMaterial() ? Icons.create : CupertinoIcons.create;

  /// Icons: Icons.crop : CupertinoIcons.crop
  IconData get crop => isMaterial() ? Icons.crop : CupertinoIcons.crop;

  /// Icons: Icons.crop_rotate : CupertinoIcons.crop_rotate
  IconData get cropRotate =>
      isMaterial() ? Icons.crop_rotate : CupertinoIcons.crop_rotate;

  /// Icons: Icons.delete : CupertinoIcons.delete
  IconData get delete => isMaterial() ? Icons.delete : CupertinoIcons.delete;

  /// Icons: Icons.eject : CupertinoIcons.eject
  IconData get eject => isMaterial() ? Icons.eject : CupertinoIcons.eject;

  /// Icons: Icons.flag : CupertinoIcons.flag
  IconData get flag => isMaterial() ? Icons.flag : CupertinoIcons.flag;

  /// Icons: Icons.flag_circle : CupertinoIcons.flag_circle
  IconData get flagCircle =>
      isMaterial() ? Icons.flag_circle : CupertinoIcons.flag_circle;

  /// Icons: Icons.folder : CupertinoIcons.folder
  IconData get folder => isMaterial() ? Icons.folder : CupertinoIcons.folder;

  /// Icons: Icons.folder_open : CupertinoIcons.folder_open
  IconData get folderOpen =>
      isMaterial() ? Icons.folder_open : CupertinoIcons.folder_open;

  /// Icons: Icons.forward : CupertinoIcons.forward
  IconData get forward => isMaterial() ? Icons.forward : CupertinoIcons.forward;

  /// Icons: Icons.fullscreen : CupertinoIcons.fullscreen
  IconData get fullscreen =>
      isMaterial() ? Icons.fullscreen : CupertinoIcons.fullscreen;

  /// Icons: Icons.fullscreen_exit : CupertinoIcons.fullscreen_exit
  IconData get fullscreenExit =>
      isMaterial() ? Icons.fullscreen_exit : CupertinoIcons.fullscreen_exit;

  /// Icons: Icons.group : CupertinoIcons.group
  IconData get group => isMaterial() ? Icons.group : CupertinoIcons.group;

  /// Icons: Icons.headphones : CupertinoIcons.headphones
  IconData get headphones =>
      isMaterial() ? Icons.headphones : CupertinoIcons.headphones;

  /// Icons: Icons.hexagon : CupertinoIcons.hexagon
  IconData get hexagon => isMaterial() ? Icons.hexagon : CupertinoIcons.hexagon;

  /// Icons: Icons.home : CupertinoIcons.home
  IconData get home => isMaterial() ? Icons.home : CupertinoIcons.home;

  /// Icons: Icons.house : CupertinoIcons.house
  IconData get house => isMaterial() ? Icons.house : CupertinoIcons.house;

  /// Icons: Icons.info : CupertinoIcons.info
  IconData get info => isMaterial() ? Icons.info : CupertinoIcons.info;

  /// Icons: Icons.keyboard : CupertinoIcons.keyboard
  IconData get keyboard =>
      isMaterial() ? Icons.keyboard : CupertinoIcons.keyboard;

  /// Icons: Icons.layers : CupertinoIcons.layers
  IconData get layers => isMaterial() ? Icons.layers : CupertinoIcons.layers;

  /// Icons: Icons.lightbulb : CupertinoIcons.lightbulb
  IconData get lightbulb =>
      isMaterial() ? Icons.lightbulb : CupertinoIcons.lightbulb;

  /// Icons: Icons.link : CupertinoIcons.link
  IconData get link => isMaterial() ? Icons.link : CupertinoIcons.link;

  /// Icons: Icons.lock : CupertinoIcons.lock
  IconData get lock => isMaterial() ? Icons.lock : CupertinoIcons.lock;

  /// Icons: Icons.lock_open : CupertinoIcons.lock_open
  IconData get lockOpen =>
      isMaterial() ? Icons.lock_open : CupertinoIcons.lock_open;

  /// Icons: Icons.loop : CupertinoIcons.loop
  IconData get loop => isMaterial() ? Icons.loop : CupertinoIcons.loop;

  /// Icons: Icons.mail : CupertinoIcons.mail
  IconData get mail => isMaterial() ? Icons.mail : CupertinoIcons.mail;

  /// Icons: Icons.map : CupertinoIcons.map
  IconData get map => isMaterial() ? Icons.map : CupertinoIcons.map;

  /// Icons: Icons.mic : CupertinoIcons.mic
  IconData get mic => isMaterial() ? Icons.mic : CupertinoIcons.mic;

  /// Icons: Icons.mic_off : CupertinoIcons.mic_off
  IconData get micOff => isMaterial() ? Icons.mic_off : CupertinoIcons.mic_off;

  /// Icons: Icons.music_note : CupertinoIcons.music_note
  IconData get musicNote =>
      isMaterial() ? Icons.music_note : CupertinoIcons.music_note;

  /// Icons: Icons.pause : CupertinoIcons.pause
  IconData get pause => isMaterial() ? Icons.pause : CupertinoIcons.pause;

  /// Icons: Icons.pause_circle : CupertinoIcons.pause_circle
  IconData get pauseCircle =>
      isMaterial() ? Icons.pause_circle : CupertinoIcons.pause_circle;

  /// Icons: Icons.percent : CupertinoIcons.percent
  IconData get percent => isMaterial() ? Icons.percent : CupertinoIcons.percent;

  /// Icons: Icons.person : CupertinoIcons.person
  IconData get person => isMaterial() ? Icons.person : CupertinoIcons.person;

  /// Icons: Icons.person_2 : CupertinoIcons.person_2
  IconData get person2 =>
      isMaterial() ? Icons.person_2 : CupertinoIcons.person_2;

  /// Icons: Icons.person_3 : CupertinoIcons.person_3
  IconData get person3 =>
      isMaterial() ? Icons.person_3 : CupertinoIcons.person_3;

  /// Icons: Icons.person_add : CupertinoIcons.person_add
  IconData get personAdd =>
      isMaterial() ? Icons.person_add : CupertinoIcons.person_add;

  /// Icons: Icons.phone : CupertinoIcons.phone
  IconData get phone => isMaterial() ? Icons.phone : CupertinoIcons.phone;

  /// Icons: Icons.photo : CupertinoIcons.photo
  IconData get photo => isMaterial() ? Icons.photo : CupertinoIcons.photo;

  /// Icons: Icons.photo_camera : CupertinoIcons.photo_camera
  IconData get photoCamera =>
      isMaterial() ? Icons.photo_camera : CupertinoIcons.photo_camera;

  /// Icons: Icons.piano : CupertinoIcons.piano
  IconData get piano => isMaterial() ? Icons.piano : CupertinoIcons.piano;

  /// Icons: Icons.pin : CupertinoIcons.pin
  IconData get pin => isMaterial() ? Icons.pin : CupertinoIcons.pin;

  /// Icons: Icons.play_arrow : CupertinoIcons.play_arrow
  IconData get playArrow =>
      isMaterial() ? Icons.play_arrow : CupertinoIcons.play_arrow;

  /// Icons: Icons.play_circle : CupertinoIcons.play_circle
  IconData get playCircle =>
      isMaterial() ? Icons.play_circle : CupertinoIcons.play_circle;

  /// Icons: Icons.play_circle_fill : CupertinoIcons.play_circle_fill
  IconData get playCircleFill =>
      isMaterial() ? Icons.play_circle_fill : CupertinoIcons.play_circle_fill;

  /// Icons: Icons.power : CupertinoIcons.power
  IconData get power => isMaterial() ? Icons.power : CupertinoIcons.power;

  /// Icons: Icons.rectangle : CupertinoIcons.rectangle
  IconData get rectangle =>
      isMaterial() ? Icons.rectangle : CupertinoIcons.rectangle;

  /// Icons: Icons.refresh : CupertinoIcons.refresh
  IconData get refresh => isMaterial() ? Icons.refresh : CupertinoIcons.refresh;

  /// Icons: Icons.repeat : CupertinoIcons.repeat
  IconData get repeat => isMaterial() ? Icons.repeat : CupertinoIcons.repeat;

  /// Icons: Icons.reply : CupertinoIcons.reply
  IconData get reply => isMaterial() ? Icons.reply : CupertinoIcons.reply;

  /// Icons: Icons.reply_all : CupertinoIcons.reply_all
  IconData get replyAll =>
      isMaterial() ? Icons.reply_all : CupertinoIcons.reply_all;

  /// Icons: Icons.rocket : CupertinoIcons.rocket
  IconData get rocket => isMaterial() ? Icons.rocket : CupertinoIcons.rocket;

  /// Icons: Icons.rotate_left : CupertinoIcons.rotate_left
  IconData get rotateLeft =>
      isMaterial() ? Icons.rotate_left : CupertinoIcons.rotate_left;

  /// Icons: Icons.rotate_right : CupertinoIcons.rotate_right
  IconData get rotateRight =>
      isMaterial() ? Icons.rotate_right : CupertinoIcons.rotate_right;

  /// Icons: Icons.search : CupertinoIcons.search
  IconData get search => isMaterial() ? Icons.search : CupertinoIcons.search;

  /// Icons: Icons.settings : CupertinoIcons.settings
  IconData get settings =>
      isMaterial() ? Icons.settings : CupertinoIcons.settings;

  /// Icons: Icons.share : CupertinoIcons.share
  IconData get share => isMaterial() ? Icons.share : CupertinoIcons.share;

  /// Icons: Icons.shield : CupertinoIcons.shield
  IconData get shield => isMaterial() ? Icons.shield : CupertinoIcons.shield;

  /// Icons: Icons.shopping_cart : CupertinoIcons.shopping_cart
  IconData get shoppingCart =>
      isMaterial() ? Icons.shopping_cart : CupertinoIcons.shopping_cart;

  /// Icons: Icons.shuffle : CupertinoIcons.shuffle
  IconData get shuffle => isMaterial() ? Icons.shuffle : CupertinoIcons.shuffle;

  /// Icons: Icons.speaker : CupertinoIcons.speaker
  IconData get speaker => isMaterial() ? Icons.speaker : CupertinoIcons.speaker;

  /// Icons: Icons.square : CupertinoIcons.square
  IconData get square => isMaterial() ? Icons.square : CupertinoIcons.square;

  /// Icons: Icons.star : CupertinoIcons.star
  IconData get star => isMaterial() ? Icons.star : CupertinoIcons.star;

  /// Icons: Icons.stop : CupertinoIcons.stop
  IconData get stop => isMaterial() ? Icons.stop : CupertinoIcons.stop;

  /// Icons: Icons.stop_circle : CupertinoIcons.stop_circle
  IconData get stopCircle =>
      isMaterial() ? Icons.stop_circle : CupertinoIcons.stop_circle;

  /// Icons: Icons.switch_camera : CupertinoIcons.switch_camera
  IconData get switchCamera =>
      isMaterial() ? Icons.switch_camera : CupertinoIcons.switch_camera;

  /// Icons: Icons.tag : CupertinoIcons.tag
  IconData get tag => isMaterial() ? Icons.tag : CupertinoIcons.tag;

  /// Icons: Icons.timelapse : CupertinoIcons.timelapse
  IconData get timelapse =>
      isMaterial() ? Icons.timelapse : CupertinoIcons.timelapse;

  /// Icons: Icons.timer : CupertinoIcons.timer
  IconData get timer => isMaterial() ? Icons.timer : CupertinoIcons.timer;

  /// Icons: Icons.today : CupertinoIcons.today
  IconData get today => isMaterial() ? Icons.today : CupertinoIcons.today;

  /// Icons: Icons.tornado : CupertinoIcons.tornado
  IconData get tornado => isMaterial() ? Icons.tornado : CupertinoIcons.tornado;

  /// Icons: Icons.tv : CupertinoIcons.tv
  IconData get tv => isMaterial() ? Icons.tv : CupertinoIcons.tv;

  /// Icons: Icons.umbrella : CupertinoIcons.umbrella
  IconData get umbrella =>
      isMaterial() ? Icons.umbrella : CupertinoIcons.umbrella;

  /// Icons: Icons.videocam : CupertinoIcons.videocam
  IconData get videocam =>
      isMaterial() ? Icons.videocam : CupertinoIcons.videocam;

  /// Icons: Icons.volume_down : CupertinoIcons.volume_down
  IconData get volumeDown =>
      isMaterial() ? Icons.volume_down : CupertinoIcons.volume_down;

  /// Icons: Icons.volume_mute : CupertinoIcons.volume_mute
  IconData get volumeMute =>
      isMaterial() ? Icons.volume_mute : CupertinoIcons.volume_mute;

  /// Icons: Icons.volume_off : CupertinoIcons.volume_off
  IconData get volumeOff =>
      isMaterial() ? Icons.volume_off : CupertinoIcons.volume_off;

  /// Icons: Icons.volume_up : CupertinoIcons.volume_up
  IconData get volumeUp =>
      isMaterial() ? Icons.volume_up : CupertinoIcons.volume_up;

  /// Icons: Icons.wifi : CupertinoIcons.wifi
  IconData get wifi => isMaterial() ? Icons.wifi : CupertinoIcons.wifi;

  /// Icons: Icons.zoom_in : CupertinoIcons.zoom_in
  IconData get zoomIn => isMaterial() ? Icons.zoom_in : CupertinoIcons.zoom_in;

  /// Icons: Icons.zoom_out : CupertinoIcons.zoom_out
  IconData get zoomOut =>
      isMaterial() ? Icons.zoom_out : CupertinoIcons.zoom_out;
}
