/// Platform Icons Example Page.
/// This file generated by script, do not edit this file directly.

/// Local SDK version information:
/// Flutter 3.10.6 • channel stable • https://github.com/flutter/flutter.git
/// Framework • revision f468f3366c (5 days ago) • 2023-07-12 15:19:05 -0700
/// Engine • revision cdbeda788a
/// Tools • Dart 3.0.6 • DevTools 2.23.1

import 'package:flutter/material.dart';
import 'package:flutter_platform_widgets/flutter_platform_widgets.dart';

import 'platform_widget_example.dart';

class IconsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      iosContentPadding: true,
      appBar: PlatformAppBar(title: Text('Platform Icons')),
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Expanded(
                  child: Text(
                    'Material',
                    textAlign: TextAlign.center,
                  ),
                ),
                Expanded(
                  child: Text(
                    'Cupertino',
                    textAlign: TextAlign.center,
                  ),
                ),
              ],
            ),
          ),
          Divider(
            thickness: 2,
          ),
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: <Widget>[
                  _IconCompared('accountCircle', PlatformIcons().accountCircle),
                  _IconCompared(
                      'accountCircleSolid', PlatformIcons().accountCircleSolid),
                  _IconCompared('add', PlatformIcons().add),
                  _IconCompared('addCircled', PlatformIcons().addCircled),
                  _IconCompared(
                      'addCircledOutline', PlatformIcons().addCircledOutline),
                  _IconCompared(
                      'addCircledSolid', PlatformIcons().addCircledSolid),
                  _IconCompared('alarm', PlatformIcons().alarm),
                  _IconCompared('arrowLeft', PlatformIcons().arrowLeft),
                  _IconCompared('arrowRight', PlatformIcons().arrowRight),
                  _IconCompared('back', PlatformIcons().back),
                  _IconCompared(
                      'batteryCharging', PlatformIcons().batteryCharging),
                  _IconCompared('batteryEmpty', PlatformIcons().batteryEmpty),
                  _IconCompared('batteryFull', PlatformIcons().batteryFull),
                  _IconCompared('bluetooth', PlatformIcons().bluetooth),
                  _IconCompared('bolt', PlatformIcons().bolt),
                  _IconCompared('book', PlatformIcons().book),
                  _IconCompared('bookmark', PlatformIcons().bookmark),
                  _IconCompared(
                      'bookmarkOutline', PlatformIcons().bookmarkOutline),
                  _IconCompared('bookmarkSolid', PlatformIcons().bookmarkSolid),
                  _IconCompared('brightness', PlatformIcons().brightness),
                  _IconCompared(
                      'brightnessSolid', PlatformIcons().brightnessSolid),
                  _IconCompared('bus', PlatformIcons().bus),
                  _IconCompared('calendarToday', PlatformIcons().calendarToday),
                  _IconCompared('camera', PlatformIcons().camera),
                  _IconCompared('car', PlatformIcons().car),
                  _IconCompared('chatBubble', PlatformIcons().chatBubble),
                  _IconCompared('checkBoxBlankOutlineRounded',
                      PlatformIcons().checkBoxBlankOutlineRounded),
                  _IconCompared('checkBoxCheckedOutlineRounded',
                      PlatformIcons().checkBoxCheckedOutlineRounded),
                  _IconCompared('checkBoxIndeterminateOutlineRounded',
                      PlatformIcons().checkBoxIndeterminateOutlineRounded),
                  _IconCompared('checkMark', PlatformIcons().checkMark),
                  _IconCompared(
                      'checkMarkCircled', PlatformIcons().checkMarkCircled),
                  _IconCompared('checkMarkCircledOutline',
                      PlatformIcons().checkMarkCircledOutline),
                  _IconCompared('checkMarkCircledSolid',
                      PlatformIcons().checkMarkCircledSolid),
                  _IconCompared('chevronLeft', PlatformIcons().chevronLeft),
                  _IconCompared('chevronRight', PlatformIcons().chevronRight),
                  _IconCompared('circle', PlatformIcons().circle),
                  _IconCompared('clear', PlatformIcons().clear),
                  _IconCompared('clearThick', PlatformIcons().clearThick),
                  _IconCompared(
                      'clearThickCircled', PlatformIcons().clearThickCircled),
                  _IconCompared('clockSolid', PlatformIcons().clockSolid),
                  _IconCompared('cloud', PlatformIcons().cloud),
                  _IconCompared('cloudDownload', PlatformIcons().cloudDownload),
                  _IconCompared(
                      'cloudDownloadSolid', PlatformIcons().cloudDownloadSolid),
                  _IconCompared('cloudSolid', PlatformIcons().cloudSolid),
                  _IconCompared('cloudUpload', PlatformIcons().cloudUpload),
                  _IconCompared(
                      'cloudUploadSolid', PlatformIcons().cloudUploadSolid),
                  _IconCompared('collections', PlatformIcons().collections),
                  _IconCompared(
                      'collectionsSolid', PlatformIcons().collectionsSolid),
                  _IconCompared(
                      'conversationBubble', PlatformIcons().conversationBubble),
                  _IconCompared('conversationBubbleOutline',
                      PlatformIcons().conversationBubbleOutline),
                  _IconCompared('create', PlatformIcons().create),
                  _IconCompared('crop', PlatformIcons().crop),
                  _IconCompared('cropRotate', PlatformIcons().cropRotate),
                  _IconCompared('dehaze', PlatformIcons().dehaze),
                  _IconCompared('delete', PlatformIcons().delete),
                  _IconCompared('deleteOutline', PlatformIcons().deleteOutline),
                  _IconCompared('deleteSolid', PlatformIcons().deleteSolid),
                  _IconCompared('downArrow', PlatformIcons().downArrow),
                  _IconCompared('edit', PlatformIcons().edit),
                  _IconCompared('eject', PlatformIcons().eject),
                  _IconCompared('ellipsis', PlatformIcons().ellipsis),
                  _IconCompared('error', PlatformIcons().error),
                  _IconCompared('eyeSlash', PlatformIcons().eyeSlash),
                  _IconCompared('eyeSlashSolid', PlatformIcons().eyeSlashSolid),
                  _IconCompared('eyeSolid', PlatformIcons().eyeSolid),
                  _IconCompared(
                      'favoriteOutline', PlatformIcons().favoriteOutline),
                  _IconCompared('favoriteSolid', PlatformIcons().favoriteSolid),
                  _IconCompared('flag', PlatformIcons().flag),
                  _IconCompared('flagCircle', PlatformIcons().flagCircle),
                  _IconCompared('folder', PlatformIcons().folder),
                  _IconCompared('folderOpen', PlatformIcons().folderOpen),
                  _IconCompared('folderSolid', PlatformIcons().folderSolid),
                  _IconCompared('forward', PlatformIcons().forward),
                  _IconCompared('fullscreen', PlatformIcons().fullscreen),
                  _IconCompared(
                      'fullscreenExit', PlatformIcons().fullscreenExit),
                  _IconCompared(
                      'gameController', PlatformIcons().gameController),
                  _IconCompared('gameControllerSolid',
                      PlatformIcons().gameControllerSolid),
                  _IconCompared('gearSolid', PlatformIcons().gearSolid),
                  _IconCompared('group', PlatformIcons().group),
                  _IconCompared('groupSolid', PlatformIcons().groupSolid),
                  _IconCompared('headphones', PlatformIcons().headphones),
                  _IconCompared('heartSolid', PlatformIcons().heartSolid),
                  _IconCompared('help', PlatformIcons().help),
                  _IconCompared('helpOutline', PlatformIcons().helpOutline),
                  _IconCompared('hexagon', PlatformIcons().hexagon),
                  _IconCompared('home', PlatformIcons().home),
                  _IconCompared('house', PlatformIcons().house),
                  _IconCompared('info', PlatformIcons().info),
                  _IconCompared('keyboard', PlatformIcons().keyboard),
                  _IconCompared('layers', PlatformIcons().layers),
                  _IconCompared('leftChevron', PlatformIcons().leftChevron),
                  _IconCompared('lightbulb', PlatformIcons().lightbulb),
                  _IconCompared('link', PlatformIcons().link),
                  _IconCompared('location', PlatformIcons().location),
                  _IconCompared('locationSolid', PlatformIcons().locationSolid),
                  _IconCompared('lock', PlatformIcons().lock),
                  _IconCompared('lockOpen', PlatformIcons().lockOpen),
                  _IconCompared('loop', PlatformIcons().loop),
                  _IconCompared('mail', PlatformIcons().mail),
                  _IconCompared('mailOutline', PlatformIcons().mailOutline),
                  _IconCompared('mailSolid', PlatformIcons().mailSolid),
                  _IconCompared('map', PlatformIcons().map),
                  _IconCompared('mic', PlatformIcons().mic),
                  _IconCompared('micOff', PlatformIcons().micOff),
                  _IconCompared('micOutline', PlatformIcons().micOutline),
                  _IconCompared('micSolid', PlatformIcons().micSolid),
                  _IconCompared('musicNote', PlatformIcons().musicNote),
                  _IconCompared('padLock', PlatformIcons().padLock),
                  _IconCompared(
                      'padlockOutline', PlatformIcons().padlockOutline),
                  _IconCompared('padlockSolid', PlatformIcons().padlockSolid),
                  _IconCompared('pause', PlatformIcons().pause),
                  _IconCompared('pauseCircle', PlatformIcons().pauseCircle),
                  _IconCompared('pawSolid', PlatformIcons().pawSolid),
                  _IconCompared('pen', PlatformIcons().pen),
                  _IconCompared('percent', PlatformIcons().percent),
                  _IconCompared('person', PlatformIcons().person),
                  _IconCompared('person2', PlatformIcons().person2),
                  _IconCompared('person3', PlatformIcons().person3),
                  _IconCompared('personAdd', PlatformIcons().personAdd),
                  _IconCompared(
                      'personAddSolid', PlatformIcons().personAddSolid),
                  _IconCompared('personOutline', PlatformIcons().personOutline),
                  _IconCompared('personSolid', PlatformIcons().personSolid),
                  _IconCompared('phone', PlatformIcons().phone),
                  _IconCompared('phoneSolid', PlatformIcons().phoneSolid),
                  _IconCompared('photo', PlatformIcons().photo),
                  _IconCompared('photoCamera', PlatformIcons().photoCamera),
                  _IconCompared(
                      'photoCameraSolid', PlatformIcons().photoCameraSolid),
                  _IconCompared('photoLibrary', PlatformIcons().photoLibrary),
                  _IconCompared(
                      'photoLibrarySolid', PlatformIcons().photoLibrarySolid),
                  _IconCompared('piano', PlatformIcons().piano),
                  _IconCompared('pin', PlatformIcons().pin),
                  _IconCompared('playArrow', PlatformIcons().playArrow),
                  _IconCompared(
                      'playArrowSolid', PlatformIcons().playArrowSolid),
                  _IconCompared('playCircle', PlatformIcons().playCircle),
                  _IconCompared(
                      'playCircleFill', PlatformIcons().playCircleFill),
                  _IconCompared(
                      'playCircleSolid', PlatformIcons().playCircleSolid),
                  _IconCompared('power', PlatformIcons().power),
                  _IconCompared('rectangle', PlatformIcons().rectangle),
                  _IconCompared('refresh', PlatformIcons().refresh),
                  _IconCompared('refreshBold', PlatformIcons().refreshBold),
                  _IconCompared('remove', PlatformIcons().remove),
                  _IconCompared('removeCircled', PlatformIcons().removeCircled),
                  _IconCompared('removeCircledOutline',
                      PlatformIcons().removeCircledOutline),
                  _IconCompared(
                      'removeCircledSolid', PlatformIcons().removeCircledSolid),
                  _IconCompared('repeat', PlatformIcons().repeat),
                  _IconCompared('reply', PlatformIcons().reply),
                  _IconCompared('replyAll', PlatformIcons().replyAll),
                  _IconCompared('rightChevron', PlatformIcons().rightChevron),
                  _IconCompared('rocket', PlatformIcons().rocket),
                  _IconCompared('rotateLeft', PlatformIcons().rotateLeft),
                  _IconCompared('rotateRight', PlatformIcons().rotateRight),
                  _IconCompared('search', PlatformIcons().search),
                  _IconCompared('settings', PlatformIcons().settings),
                  _IconCompared('settingsSolid', PlatformIcons().settingsSolid),
                  _IconCompared('share', PlatformIcons().share),
                  _IconCompared('shareSolid', PlatformIcons().shareSolid),
                  _IconCompared('shield', PlatformIcons().shield),
                  _IconCompared('shoppingCart', PlatformIcons().shoppingCart),
                  _IconCompared('shuffle', PlatformIcons().shuffle),
                  _IconCompared('speaker', PlatformIcons().speaker),
                  _IconCompared('square', PlatformIcons().square),
                  _IconCompared('star', PlatformIcons().star),
                  _IconCompared(
                      'starCircleSolid', PlatformIcons().starCircleSolid),
                  _IconCompared('stop', PlatformIcons().stop),
                  _IconCompared('stopCircle', PlatformIcons().stopCircle),
                  _IconCompared('switchCamera', PlatformIcons().switchCamera),
                  _IconCompared(
                      'switchCameraSolid', PlatformIcons().switchCameraSolid),
                  _IconCompared('tag', PlatformIcons().tag),
                  _IconCompared('tagOutline', PlatformIcons().tagOutline),
                  _IconCompared('tagSolid', PlatformIcons().tagSolid),
                  _IconCompared('thumbDown', PlatformIcons().thumbDown),
                  _IconCompared(
                      'thumbDownOutlined', PlatformIcons().thumbDownOutlined),
                  _IconCompared('thumbUp', PlatformIcons().thumbUp),
                  _IconCompared(
                      'thumbUpOutlined', PlatformIcons().thumbUpOutlined),
                  _IconCompared('time', PlatformIcons().time),
                  _IconCompared('timeSolid', PlatformIcons().timeSolid),
                  _IconCompared('timelapse', PlatformIcons().timelapse),
                  _IconCompared('timer', PlatformIcons().timer),
                  _IconCompared('today', PlatformIcons().today),
                  _IconCompared('tornado', PlatformIcons().tornado),
                  _IconCompared('train', PlatformIcons().train),
                  _IconCompared('tv', PlatformIcons().tv),
                  _IconCompared('umbrella', PlatformIcons().umbrella),
                  _IconCompared('upArrow', PlatformIcons().upArrow),
                  _IconCompared('videoCamera', PlatformIcons().videoCamera),
                  _IconCompared(
                      'videoCameraSolid', PlatformIcons().videoCameraSolid),
                  _IconCompared('videocam', PlatformIcons().videocam),
                  _IconCompared('volumeDown', PlatformIcons().volumeDown),
                  _IconCompared('volumeMute', PlatformIcons().volumeMute),
                  _IconCompared('volumeOff', PlatformIcons().volumeOff),
                  _IconCompared('volumeUp', PlatformIcons().volumeUp),
                  _IconCompared('wifi', PlatformIcons().wifi),
                  _IconCompared('wifiOff', PlatformIcons().wifiOff),
                  _IconCompared('zoomIn', PlatformIcons().zoomIn),
                  _IconCompared('zoomOut', PlatformIcons().zoomOut),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _IconCompared extends StatelessWidget {
  _IconCompared(this.title, this.icon);

  final String title;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    return PlatformWidgetExample(
      title: title,
      showBothPlatforms: true,
      builder: (_, __) => Icon(icon),
    );
  }
}
